name: dart_json_package
description: dart json package info
version: 1.0.2
# homepage: https://www.example.com
repository: https://github.com/hkloudou/darts/tree/main/dart_json_package
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  # json_annotation: ^4.6.0

dev_dependencies:
  lints: ^2.0.0
  # test: ^1.16.0
