name: flutter_base_loader
description: easy to load packageInfo deviceInofo and platformInfo,and provice a loadpage to make app more powerful
version: 0.0.9+1
repository: https://github.com/hkloudou/darts/tree/main/flutter_base_loader
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: "^1.4.2"
  device_info_plus: "^3.2.3"
  shared_preferences: "^2.0.15"
  uuid: ^3.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
#   # The "flutter_lints" package below contains a set of recommended lints to
#   # encourage good coding practices. The lint set provided by the package is
#   # activated in the `analysis_options.yaml` file located at the root of your
#   # package. See that file for information about deactivating specific lint
#   # rules and activating additional ones.
# flutter_lints: any
