name: flutter_base_loader
description: easy to load packageInfo deviceInofo and platformInfo,and provice a loadpage to make app more powerful
version: 0.1.0
repository: https://github.com/hkloudou/darts/tree/main/flutter_base_loader
environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: "^5.0.1"
  device_info_plus: "^9.1.1"
  shared_preferences: "^2.2.2"
  uuid: ^4.2.1
# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^2.0.0
#   # The "flutter_lints" package below contains a set of recommended lints to
#   # encourage good coding practices. The lint set provided by the package is
#   # activated in the `analysis_options.yaml` file located at the root of your
#   # package. See that file for information about deactivating specific lint
#   # rules and activating additional ones.
# flutter_lints: any
