name: dart_mqtt
description: a mqtt library to easy connect via tcp/ssl,dependence xtransport,developing,not stable.
version: 1.0.2+4
repository: https://github.com/hkloudou/darts/tree/main/dart_mqtt
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  xtransport: ^0.0.4+7
  # path: ^1.8.0
  # xtransport:
  #   path: ../xtransport/
dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
