name: doh
description: doh client to resolve dns, include alidns,google dns and cloudflare
version: 0.0.3
repository: https://github.com/hkloudou/darts/tree/main/doh

environment:
  sdk: '>=2.17.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
